---
title: "Exploration with CSVs"
author: "Malia Cortez"
date: "2024-08-11"
output: html_document
---

```{r setup, include=FALSE}
# data manipulation and reading
library(dplyr)
library(tidyverse)
library(tidyr)
library(stringr)
library(data.table)
library(readxl)
library(tigris)

# statistics
library(stats)

# mapping and plotting
library(ggplot2)
library(terra)
library(mapdeck)
library(mapboxapi)
library(sf)

# modeling
library(tree)
library(randomForest)
library(randomForestExplainer)
library(keras)

# extracting survey/IPUMS/census data
#library(survey)
#library(srvyr)
library(ipumsr)
library(tidycensus)
```

## Load Data
- Flows from Seattle-Tacoma-Bellevue metro area. 
- Changes from 2010 to 2020.
- Flows in 2020.
```{r cars}
race <- read.csv("data/race_2010-2020.csv")
housing <- read.csv("data/msa_med_housing_2011-2020.csv")
migrations <- read.csv("data/sea_mig_2020.csv")

# load in pop data eventually...
```

## Including Plots
Lots of movement to the South for Black populations (ATL GA, Dallas FT Worth + Houston TX), with DC in 3rd place.
```{r}
# race data
head(race)

metro_race <- race %>% 
  filter(str_detect(CBSA, "Metro"))

# which msa saw most positive change in Black pop?
ggplot(metro_race %>% 
         arrange(desc(chg_black_2010_2020)) %>% 
         slice_head(n = 10),
       aes(x = reorder(CBSA, chg_black_2010_2020),
           y = chg_black_2010_2020)) +
  geom_bar(stat = "identity") +
  labs(title = "Metro Areas with Most Positive Change in Black Population",
       x = "MSA",
       y = "Value") +
  coord_flip()

# which msa saw most negative change in Black pop?
ggplot(metro_race %>% 
         arrange(chg_black_2010_2020) %>% 
         slice_head(n = 10),
       aes(x = reorder(CBSA, -chg_black_2010_2020),
           y = chg_black_2010_2020)) +
  geom_bar(stat = "identity") +
  labs(title = "Metro Areas with Most Negative Change in Black Population",
       x = "MSA",
       y = "Value") +
  coord_flip()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
